### ISSUE TITLE
Errors and logs in colab

### ISSUE THREAD

**Issue by domoritz** [manzt/quak#19]
I tried quak in colab and it works out of the box which is amazing: https://colab.research.google.com/drive/13gA8FfYbwiOIfJLAiXOtjjLHeeLybVqT?usp=sharing. Unfortunately, I see a bunch of errors and logs below the table that are not useful for users. 

<img width="1268" alt="Screenshot 2024-07-26 at 07 46 17" src="https://github.com/user-attachments/assets/ea31545c-22d2-49a4-ac14-50f58b13be56">

**Comment by manzt** [comment]
This is good to know. I forgot that Google Colab prints logging errors directly below the output.

I also can reproduce these errors on the client when trying out the wasm example with the same data (`npx vite`). There is a parser for the SQL generated creating a tmp index:

```
DataCubeIndexer.js:132 Error: Parser Error: syntax error at or near "50000000000"
LINE 1: ...82439e AS SELECT (TIME_BUCKET(INTERVAL 50000000000 year, "date_of_birth")) AS ...
```


<img width="1309" alt="image" src="https://github.com/user-attachments/assets/7a41b979-7723-41d4-98e2-d572094e1fdb">

**Comment by manzt** [comment]
ahh ok i misunderstood!
