### ISSUE TITLE
Dual Scrolling in Visual Studio Code

### ISSUE THREAD

**Issue by dakoop** [manzt/quak#27]
In VSCode Jupyter notebooks (macOS), the scroll event seems to be consumed by both the notebook and the table, leading to difficult scrolling interactions since the notebook is moving while trying to scroll the table. This is not an issue in JupyterLab.

quak: 0.1.2
OS: macOS 14.5
VSCode: 1.9.1
VSCode Jupyter: v2024.6.0
JupyterLab: 4.2.4

**Comment by manzt** [comment]
I'm aware of some prior issues with scroll behavior for widgets in VS Code, however, it seems like they are resolved or at least the insiders version worked for this individual a few months ago.

- https://github.com/microsoft/vscode-jupyter/issues/15575

Perhaps we need to stop propagation for scroll events. I'm preparing for a meeting with my PhD committee, so I won't have time to look further until maybe next week.

**Comment by dakoop** [comment]
Sure. Just wanted to log a few issues I noticed when testing quak out before I forgot about them

**Comment by manzt** [comment]
Same issue in Positron IDE.

**Comment by manzt** [comment]
Should be fixed in v0.1.5
