### ISSUE TITLE
Duplicate Second Row

### ISSUE THREAD

**Issue by dakoop** [manzt/quak#28]
When loading using polars, I noticed that the second row seems to be duplicated and added above the first row. It is also numbered as 1.

<img width="1036" alt="Screenshot 2024-07-30 at 3 34 27 PM" src="https://github.com/user-attachments/assets/635ca40d-2d93-447e-a0c4-32f5fda9983d">

data: [Chicago Food Inspections](https://data.cityofchicago.org/Health-Human-Services/Food-Inspections/4ijn-s7e5/about_data)
quak: 0.1.2
polars: 1.2.1
pyarrow: 17.0.0
OS: macOS 14.5
JupyterLab: 4.2.4

**Comment by dakoop** [comment]
Seems to be the initial load only. If I select some subset and hit reset, everything is ok. Also shows up in the initial load with pandas (2.2.2)

**Comment by manzt** [comment]
I've noticed this as well. Also can reproduce on the standalone website (https://manzt.github.io/quak).

**Comment by manzt** [comment]
Got to the bottom of it in #36. I'll make a release today.
