### ISSUE TITLE
Failure to load model in legacy Jupyter Notebook

### ISSUE THREAD

**Issue by cpsievert** [manzt/quak#29]
Cool package! I was eager to see how it works with [Shiny via shinywidgets](https://shiny.posit.co/py/docs/jupyter-widgets.html), but it seems something in my Python environment is off. I get the following JS error when trying to render the `Widget` in Jupyter:

<img width="937" alt="Screenshot 2024-07-30 at 4 20 15 PM" src="https://github.com/user-attachments/assets/d282c142-e6d4-4299-a234-043aa033609a">

And here is more info about that error:

![Screenshot 2024-07-30 at 4 17 50 PM](https://github.com/user-attachments/assets/716f0b45-d74c-419f-9342-79bcbe112d99)

Happy to offer any more information you think might be relevant (or even pair on it, if you'd like)

**Comment by manzt** [comment]
This error usually comes up with widgets if you `%pip` or `!pip` install anywidget for the first time in a _running_ jupyter environment. Please try shutting down the Jupyter server and restarting (not just restarting the kernel).

**Comment by manzt** [comment]
Hard to know for sure if this is the issue (expanding the `Error: Script error for "anywidget"` might provide more context).

**Comment by cpsievert** [comment]
I still get the same error after shutting down the server -- maybe it's because I have an old version of the notebook?

```python
$ jupyter notebook --version
6.5.2
``` 

Good news though -- it does work with JupyterLab:

```python
$ jupyter lab --version
3.5.3
``` 

And also the Python kernel that I'm using is 3.12.

**Comment by manzt** [comment]
Oh interesting, thanks for sharing. I'll have a look.

**Comment by manzt** [comment]
Can you share how you made the Python environment and the version of Python?

**Comment by manzt** [comment]
Closing as I haven't been able to reproduce. Please let me know if after creating a fresh environment you still have troubles!
