### ISSUE TITLE
Support dates histogram

### ISSUE THREAD

**Issue by svittoz** [manzt/quak#35]
Thanks for this nice library !

In the example you provide (**athletes.csv**), `date_of_birth` column histogram is not displayed. 

Is it a feature on your roadmap ?

**Comment by manzt** [comment]
Hi, definitely a feature that would be great to have! There is not official roadmap at the moment and happy to support a PR.

**Comment by manzt** [comment]
Hey! I took a look into this today, and I think it's actually an upstream issue in mosaic! https://github.com/uwdata/mosaic/issues/484.

**Comment by manzt** [comment]
Date histograms should now work as of v0.2!
