### ISSUE TITLE
Visualize on the web?

### ISSUE THREAD

**Issue by youssefabdelm** [manzt/quak#68]
Hey guys I'm trying to use this library but on the web but struggling. Is there some guide on how to do this? 

E.g. instead of jupyter, I'd like to display this table in html + js, or a svelte app. Somehow you guys are able to achieve this via the demo?

**Comment by declann** [comment]
If your data is public you might be able to use the web app at https://manzt.github.io/quak/

It has a URL feature (poorly exposed?), for example the example link to load athletes dataset includes a URL: https://manzt.github.io/quak/?source=https://pub-2fc10ef67241467c8327dac35d878da9.r2.dev/athletes.parquet

If you need to customise it, the code for the app is [in](https://github.com/manzt/quak/blob/main/index.html) the repo. You need to install deno and do `deno run vite`

**Comment by youssefabdelm** [comment]
@declann Thanks so much! Yeah I was essentially trying to customize it (want to have data visualization inside cells)
